#!/bin/bash

echo "SYLAR_PROJECT_DIR=${SYLAR_PROJECT_DIR}"
echo "SYLAR_PROJECT_SCRIPTS_DIR=${SYLAR_PROJECT_SCRIPTS_DIR}"

echo "SYLAR_DATA_SRC_HOME_DIR=${SYLAR_DATA_SRC_HOME_DIR}"
echo "SYLAR_DATA_SRC_IN_DIR=${SYLAR_DATA_SRC_IN_DIR}"
echo "SYLAR_CURR_HOME_DIR=${SYLAR_CURR_HOME_DIR}"
echo "SYLAR_CRYPTO_HOME_DIR=${SYLAR_CRYPTO_HOME_DIR}"

echo "SYLAR_IN=${SYLAR_IN}"
echo "SYLAR_CSV=${SYLAR_CSV}"

echo "LOGS_PARENT_DIR=${LOGS_PARENT_DIR}"
echo "STOOQ_PNG_PARENT_DIR=${STOOQ_PNG_PARENT_DIR}"
echo "STOOQ_CSV_PARENT_DIR=${STOOQ_CSV_PARENT_DIR}"
echo "STOOQ_CSV_B15M_PARENT_DIR=${STOOQ_CSV_B15M_PARENT_DIR}"
echo "B15M_PARENT_DIR=${B15M_PARENT_DIR}"